#include "Account.hpp"
#include <iostream>

int main(void)
{
    Account yeye(20);
    Account lele(30);

    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    std::cout << "Make Deposit" << std::endl;
    yeye.makeDeposit(15);
    lele.makeDeposit(200);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << "Make Withdrawal" << std::endl;
    yeye.makeWithdrawal(30);
    lele.makeWithdrawal(50);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << "Make Deposit" << std::endl;
    yeye.makeDeposit(35);
    lele.makeDeposit(40);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << std::endl;
    std::cout << std::endl;
    std::cout << "Make Withdrawal" << std::endl;
    yeye.makeWithdrawal(65);
    lele.makeWithdrawal(100);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << "Make Deposit" << std::endl;
    yeye.makeDeposit(65);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << "Make Withdrawal" << std::endl;
    lele.makeWithdrawal(1000);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << "Make Withdrawal" << std::endl;
    lele.makeWithdrawal(100);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << "Make Withdrawal" << std::endl;
    yeye.makeWithdrawal(105);
    std::cout << std::endl;
    std::cout << "Info" << std::endl;
    yeye.displayStatus();
    lele.displayStatus();
    std::cout << std::endl;
    Account::displayAccountsInfos();
    std::cout << std::endl;
    std::cout << "Destructor" << std::endl;
}